# Generated by Django 4.2 on 2024-03-30 18:50

import backend.validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAvailibility",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date_time",
                    models.DateTimeField(
                        validators=[backend.validators.validate_datetime]
                    ),
                ),
                (
                    "end_date_time",
                    models.DateTimeField(
                        validators=[backend.validators.validate_datetime]
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="scheduled_events", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
